language: C

sudo: false

addons:
  apt:
    packages:
      - autopoint
      - libreadline-dev
      - wget
      - texinfo

# run the tests
#script: autoreconf -i && ./configure --enable-maintainer-mode && make update && (cd doc && make stamp-vti) && make && TRAVIS=1 make check
script: autoreconf -i && ./configure && make update && (cd doc && make stamp-vti) && make && TRAVIS=1 make check
