os: linux

# 'xenial': one test of 'functions/wildcard' fails
# On bionic it works out of the box
dist: bionic

language: c

install:
  # Prerequisites
  - sudo apt-get install autopoint libreadline-dev wget texinfo gettext

# run the tests
script: autoreconf -i && ./configure && make po-update && (cd doc && make stamp-1 stamp-vti) && make && make check
